version: '3'
services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

  disque:
    image: richnorth/disque
    ports:
      - "7711:7711"
    expose:
      - 7711

  impraise-worker-watch:
    depends_on:
      - disque
      - redis
    build: .
    command: watch close-write
    volumes:
      - /tmp/sftp/home:/home
    environment:
      WATCH_DIRECTORY: /home
      DISQUE_QUEUE: 894e6396-a38a-4c63-8eac-a453376bc26e
      DISCO_REDIS: redis:6379
      DISCO_DISQUE: disque:7711

  impraise-worker-consume:
    depends_on:
      - disque
      - redis
    build: .
    command: consume jobs
    volumes:
      - /tmp/sftp/home:/home
    environment:
      WATCH_DIRECTORY: /home
      DISQUE_QUEUE: 894e6396-a38a-4c63-8eac-a453376bc26e
      DISCO_RETHINKDB: rethinkdb:28015
      DISCO_DISQUE: disque:7711
