version: '3'
services:

  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
    expose:
      - 28015

  sftp:
    image: atmoz/sftp
    volumes:
      - /tmp/sftp/home:/home
    ports:
      - "2222:22"
    command: impraise:impraise:::upload

  disque:
    image: richnorth/disque
    expose:
      - 7711

  impraise-worker-watch:
    depends_on:
      - disque
      - rethinkdb
    build: .
    command: watch close-write
    volumes:
      - /tmp/sftp/home:/home
    environment:
      WATCH_DIRECTORY: /home
      DISQUE_QUEUE: 894e6396-a38a-4c63-8eac-a453376bc26e
      DISCO_RETHINKDB: rethinkdb:28015
      DISCO_DISQUE: disque:7711

  impraise-worker-consume:
    depends_on:
      - disque
      - rethinkdb
    build: .
    command: consume jobs
    volumes:
      - /tmp/sftp/home:/home
    environment:
      WATCH_DIRECTORY: /home
      DISQUE_QUEUE: 894e6396-a38a-4c63-8eac-a453376bc26e
      DISCO_RETHINKDB: rethinkdb:28015
      DISCO_DISQUE: disque:7711
